default vesamenu.c32
#default menu.c32
#default chain.c32
prompt 0
timeout 300

F1 f1.txt
F2 f2.txt
F3 f3.txt
F4 f4.txt
F5 f5.txt
F6 f6.txt
F7 f7.txt
F8 f8.txt
F9 f9.txt
F0 f10.txt

MENU BACKGROUND /splash.png

#MENU INCLUDE /info.txt

MENU TITLE LiveUSB Custom, Pressez [tab] pour afficher les options

LABEL Live
  MENU DEFAULT Mode live
  kernel /vmlinuz
  append  locale=fr_FR.UTF-8 bootkbd=fr console-setup/layoutcode=fr console-setup/variantcode=nodeadkeys file=/preseed/ubuntu boot=casper initrd=/initrd.gz root=/dev/ram rw union=aufs splash quiet --

LABEL Persistent
  menu label Mode persistent
  kernel /vmlinuz
  append  locale=fr_FR.UTF-8 bootkbd=fr console-setup/layoutcode=fr console-setup/variantcode=nodeadkeys file=/preseed/ubuntu boot=casper persistent initrd=/initrd.gz root=/dev/ram rw union=aufs splash quiet --

MENU TABMSG Pressez [Tab] pour afficher les options de boot
