#!/bin/bash
# v2 23/12/2008

case $1 in 
start)

if [[ $(cat /proc/cmdline | grep "proprio=false") ]]; then
	exit 0
fi

## tue usplash
usplash_down
chvt 2
chvt 8

echo -e "Configuration graphique... \n"

# script de génération de fichier de configuration pour Xorg
DRV_NVIDIA="$(lspci -nn | grep -i vga | grep -Eiw "nvidia|geforce|quadro|riva|vanta|aladdin")"
DRV_ATI="$(lspci -nn | grep -i vga | grep -iw ati)"
DIST=$(grep "CODENAME" /etc/lsb-release | sed 's/.*=//')
## remet a jour liste des modules...
depmod -ae

function GENXORG() {

test=$(lspci -b | grep VGA | awk '{print $1}')
testa=$(echo "$test" | sed 's/:.*//')
testb=$(echo "$test" | sed 's/\..*//;s/.*://')
testc=$(echo "$test" | sed 's/.*\.//')

if [[ "$testa" != "0" && "$testa" -lt "10" ]]; then
	testa=$(echo "$testa" | cut -c 2)
fi

if [[ "$testb" != "0" && "$testb" -lt "10" ]]; then
	testb=$(echo "$testb" | cut -c 2)
fi

if [[ "$testc" != "0" && "$testc" -lt "10" ]]; then
	testc=$(echo "$testc" | cut -c 2)
fi

BUSID="BusID \"PCI:$testa:$testb:$testc\""
KeyMap=$(grep "XKBLAYOUT=" /etc/default/console-setup | cut -d\" -f2)

dpkg-reconfigure -fnoninteractive --no-reload -phigh xserver-xorg &>/dev/null

sed -i 's/Option.*\"XkbLayout\".*/Option      \"XkbLayout\" \"'"$KeyMap"'\"/' /etc/X11/xorg.conf &>/dev/null
sed -i '/BusID/d' /etc/X11/xorg.conf

if [[ -n "$DRIVER" && $DRIVER = "radeonhd" ]]; then
	sed -i 's/Section \"Device\"\n*/Section \"Device\"\n\t Driver \"'$DRIVER'\"\n\t Option  \"DRI\"\n\t '"$BUSID"'/' /etc/X11/xorg.conf
else
	sed -i 's/Section \"Device\"\n*/Section \"Device\"\n\t Driver \"'$DRIVER'\"\n\t '"$BUSID"'/' /etc/X11/xorg.conf

fi

echo -e "Xorg pour driver $DRIVER genere... OK"

}

cd /tmp
## recupere liste des id de carte 
wget -q http://ubuntu.rabbattskeudz.com/1.0-71xx
wget -q http://ubuntu.rabbattskeudz.com/1.0-96xx
wget -q http://ubuntu.rabbattskeudz.com/177.80
wget -q http://ubuntu.rabbattskeudz.com/atilegacy
wget -q http://ubuntu.rabbattskeudz.com/atinew
	
### version pilotes
current_ati="8.552"

if [[ "$DIST" = "hardy" || "$DIST" = "intrepid" ]] ;then
	mkdir /usr/X11R6/lib/modules &>/dev/null
	mkdir /usr/X11R6/lib/modules/dri &>/dev/null
	ln -s /usr/X11R6/lib/modules/dri/fglrx_dri.so /usr/lib/dri/fglrx_dri.so &>/dev/null
fi

echo -n "Detection du pilote graphique..."

#reactiver si desactivé dans: /etc/default/linux-restricted-modules-common
sed -i "s/^DISABLED_MODULES=\"\"/DISABLED_MODULES=\"fglrx nvidia\"/" /etc/default/linux-restricted-modules-common

echo -e "demarre la configuration..."

# NVIDIA detecté, prendre driver proprio si dispo
if [ "$DRV_NVIDIA" ]; then

dialog --title "Choix du pilote graphique" \
--checklist "Choisissez le driver a utiliser
" 10 100 3 \
"Nv" "Nouveau pilote ati libre base sur les specifications Ati" off \
"Nvidia" "Driver propriétaire Ati" off 2>/tmp/menu.tmp.$$
CHOICE=$(cat /tmp/menu.tmp.$$ | sed 's/\"//g')

rm /tmp/menu.tmp.$$

case $CHOICE in
	Nv)
		DRIVER="nv"
		GENXORG
	;;
	Nvidia)
		glxversion="177"
		legacyversion="173"
		## prend l id de la carte
		cardid=$(lspci -nn | grep VGA | grep NVidia | awk '{print $NF}' | sed 's/.*://;s/]//')
		pci="0x$cardid"

		# The driver ids:
		nvidiaglx="$(cat /tmp/177.80)"
		nvidiaglxlegacy="$(cat /tmp/1.0-96xx)"
		speciallegacy="$(cat /tmp/1.0-71xx)"

		#test quel driver nvidia utiliser
		cd /opt/reserve
		
		if [[ $(echo -e "$nvidiaglx" | grep "$pci") ]]; then
			echo -n "nvidia-glx-new"
			#nvidia-glx
			dpkg -i nvidia-${glxversion}-kernel* nvidia-glx-${glxversion}* nvidia-settings* nvidia-${glxversion}-modaliases*
		elif [[ $(echo -e "$nvidiaglxlegacy" | grep "$pci") ]]; then
			echo -n "nvidia-glx-legacy"
			#nvidia-glx-legacy
			dpkg -i nvidia-${legacyversion}-kernel* nvidia-glx-${legacyversion}* nvidia-${legacyversion}-modaliases* nvidia-settings*
		else
			echo -n "nvidia-glx-new"
			#nvidia-glx-new
			dpkg -i nvidia-${glxversion}-kernel* nvidia-glx-${glxversion}* nvidia-settings* nvidia-${glxversion}-modaliases*
		fi
		
		#configure xorg
		nvidia-xconfig -d 24 --enable-all-gpus --keyboard=$(grep "XKBLAYOUT=" /etc/default/console-setup | cut -d\" -f2) --keyboard-driver=keyboard --force-generate --logo --randr-rotation --silent --add-argb-glx-visuals
		modprobe nvidia
		;;
		*)
		## config par defaut
		DRIVER="nv"
		GENXORG
	;;
esac


##############################################
# ATI detecté, prendre driver proprio si dispo
elif [ "$DRV_ATI" ]; then

## prend l id de la carte
cardid=$(lspci -nn | grep VGA | grep ATI | awk '{print $NF}' | sed 's/.*://;s/]//')
getpci="0x$cardid"

dialog --title "Choix du pilote graphique" \
--checklist "Choisissez le driver a utiliser
" 10 100 3 \
"RadeonHd" "Nouveau pilote ati libre base sur les specifications Ati" off \
"Fglrx" "Driver propriétaire Ati" off \
"Radeon" "Pilote radeon classique" off 2>/tmp/menu.tmp.$$
CHOICE=$(cat /tmp/menu.tmp.$$ | sed 's/\"//g')

rm /tmp/menu.tmp.$$

case $CHOICE in
	Fglrx)
	    cd /opt/reserve
		DRIVER="fglrx"
		dpkg -i xorg-driver-fglrx* fglrx-kernel-source* fglrx-amdcccle* fglrx-modaliases*
		echo -e "Configuration Xorg pour Ati"
		
		## vire radeon si deja charge
		if [[ $(lsmod | egrep -iw "drm|radeon") ]]; then
			rmmod radeon drm
		fi
		## charge le module
		rmmod radeon drm &>/dev/null
		modprobe fglrx
		
## essaye de detecter la resolution ideale et si nok 
## lance un dialog qui demande laresolution a utiliser...

## detection
res="$(ddcprobe | grep dtiming | sed 's/.*: //;s/@.*//')"

## si vide affiche le dialogue
if [ -z "$res" ]; then
dialog --title "Configuration fglrx" \
--inputbox "Resolution non detectee !\n\n
Indiquez la resolution que vous souhaitez utiliser\n\n
Exemple: 1280x1024\n\n" 100 100 "$res" 2>/tmp/menu.tmp.$$
res=$(cat /tmp/menu.tmp.$$ | sed 's/\"//g')
fi

## genere le xorg en sortie...
echo -e "Genere Xorg.conf avec aticonfig et resolution: $res \n"
aticonfig --initial --resolution=0,"${res}" &>/dev/null

echo -e "Pilote radeon installe et configure... [OK]"

;;
	
	RadeonHd)
		if [ ! -e "/usr/lib/xorg/modules/drivers/radeonhd_drv.so" ]; then
			echo -e "Le Driver Radeon HD est inexistant, repasse sur radeon... \n"
			DRIVER="radeon"
		else
			echo -e "Activation du pilote RadeonHd"
			DRIVER="radeonhd"
		fi
		## recree xorg.conf
		GENXORG
	;;
	
	Radeon)
		DRIVER="radeon"
		## recree xorg.conf
	GENXORG
	;;
	
	*)
		DRIVER="radeon"
		## recree xorg.conf
		GENXORG
	;;
esac

else # ni nvida ni ati...
	echo -e "Configuration basique de Xorg"
	DRIVER="vesa"
	GENXORG
fi
#rm -R /opt/reserve

;; ## fin case start)
esac

exit 0

