#!/bin/bash
#
# Note that output goes into the .xsession-errors file for easy debugging
#

# extrait le background de l utilisateur demandé
WALLPAPER=$(sudo -u $USER gconftool-2 --get /desktop/gnome/background/picture_filename)
# ses options
MODE=$(sudo -u $USER gconftool-2 --get /desktop/gnome/background/picture_options)
# le nom de l image
WALLNAME="$(basename $WALLPAPER)"
# extrait la couleur principale (au cas ou wallpaper ne serait pas detecte)
PRIMARY_COLOR=$(sudo -u $USER gconftool-2 --get /desktop/gnome/background/primary_color)

# Check if the wallpaper file exists. If yes - draw it, if no - use primary background color
## resize img
resolution="$(sudo ddcprobe | grep dtiming | sed 's/.*: //;s/@.*//')"
convert -resize ${resolution}! "$WALLPAPER" "/tmp/$WALLNAME" &&

if [ -e "$WALLPAPER" ] && [ -f "$WALLPAPER" ] ; then
    xloadimage -onroot -fullscreen "/tmp/$WALLNAME"
else
    xsetroot -cursor_name left_ptr -solid "$PRIMARY_COLOR"
fi

exit 0
